/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  //const group = useRef();
  const { nodes, materials } = useGLTF("./LUNA.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Esfera.geometry}
        material={materials.Material}
        scale={3.67}
      />
    </group>
  );
}

useGLTF.preload("./LUNA.gltf");
